version: "3.9"

services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app/dbt
    environment:
      DBT_PROFILES_DIR: /app/dbt
      DUCKDB_PATH: /app/data/lakehouse.duckdb
    command: tail -f /dev/null

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    user: "0:0"
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      PYTHONPATH: /home/airflow/.local/lib/python3.11/site-packages:/app
      PATH: /home/airflow/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ./airflow:/opt/airflow
      - ./:/app
    working_dir: /opt/airflow
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    user: "0:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /home/airflow/.local/lib/python3.11/site-packages:/app
      PATH: /home/airflow/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ./airflow:/opt/airflow
      - ./:/app
    working_dir: /opt/airflow
    command: scheduler
